# Generated by Django 4.2.1 on 2023-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Default Author', max_length=100)),
                ('Circuit_Design', models.IntegerField(default=0, null=True)),
                ('Control_Systems', models.IntegerField(default=0, null=True)),
                ('Power_Electronics', models.IntegerField(default=0, null=True)),
                ('Analog_Communication', models.IntegerField(default=0, null=True)),
                ('R_F', models.IntegerField(default=0, null=True)),
                ('C_P_P', models.IntegerField(default=0, null=True)),
                ('Electrical_System', models.IntegerField(default=0, null=True)),
                ('C_A_D', models.IntegerField(default=0, null=True)),
                ('P_C_B', models.IntegerField(default=0, null=True)),
                ('Lab_View', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
