# Generated by Django 4.2.1 on 2023-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careertool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Default Author', max_length=100)),
                ('Circuit_Design', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_View', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Control_Systems', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Power_Electronics', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analog_Communication', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_F', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_P_P', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electrical_System', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_A_D', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='s9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_C_B', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='db',
        ),
    ]
