# Generated by Django 4.2.1 on 2023-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careertool', '0002_s1_s10_s2_s3_s4_s5_s6_s7_s8_s9_delete_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='c1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_base', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_C_B', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_architecture', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyber_security', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networking', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_development', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_ml', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_designer', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_skils', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_communication', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
