# Generated by Django 4.2.1 on 2023-08-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careertool', '0003_c1_c10_c2_c3_c4_c5_c6_c7_c8_c9'),
    ]

    operations = [
        migrations.CreateModel(
            name='cs10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_skills', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='c1',
            new_name='cs1',
        ),
        migrations.RenameModel(
            old_name='c2',
            new_name='cs2',
        ),
        migrations.RenameModel(
            old_name='c3',
            new_name='cs3',
        ),
        migrations.RenameModel(
            old_name='c4',
            new_name='cs4',
        ),
        migrations.RenameModel(
            old_name='c5',
            new_name='cs5',
        ),
        migrations.RenameModel(
            old_name='c6',
            new_name='cs6',
        ),
        migrations.RenameModel(
            old_name='c7',
            new_name='cs7',
        ),
        migrations.RenameModel(
            old_name='c8',
            new_name='cs8',
        ),
        migrations.RenameModel(
            old_name='c9',
            new_name='cs9',
        ),
        migrations.DeleteModel(
            name='c10',
        ),
        migrations.RenameField(
            model_name='cs8',
            old_name='communication_skils',
            new_name='communication_skills',
        ),
    ]
