# Generated by Django 4.2.1 on 2023-08-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careertool', '0004_cs10_rename_c1_cs1_rename_c2_cs2_rename_c3_cs3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cs8',
            old_name='communication_skills',
            new_name='data_science',
        ),
        migrations.RenameField(
            model_name='cs9',
            old_name='technical_communication',
            new_name='communication_skills',
        ),
    ]
