# Generated by Django 4.2.1 on 2023-08-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careertool', '0005_rename_communication_skills_cs8_data_science_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cs10',
        ),
        migrations.DeleteModel(
            name='cs9',
        ),
    ]
